### ISSUE TITLE
some explanation on how to run this code

### ISSUE THREAD

**Issue by nicosalto** [smcameron/curly-vortex#2]
Hi,
This looks really great and iam trying to run the code without success.
What is the .pde file extention ? does it need to be run from a specific package ? Or do i need to compile this ?

**Comment by smcameron** [comment]
It is in a Java-like language called "Processing" that is intended for "creative coding" or "recreational programming" kinds of things.   See http://processing.org  If you download and run the processing binary, you get a little IDE (very similar to the arduino IDE, if you've seen that) and you can open up the pde file from there and run it.

**Comment by nicosalto** [comment]
Thanks a lot for the quick answer, i downloaded processing and it works really well!
Only side note, you need to use processing 2.2.1
